set(HASCIICAM_AALIB_SOURCES
    src/aalib/aaattrs.c
    src/aalib/aacurkbd.c
    src/aalib/aacurmou.c
    src/aalib/aacurrfnt.c
    src/aalib/aacurses.c
    src/aalib/aaedit.c
    src/aalib/aafastre.c
    src/aalib/aaflush.c
    src/aalib/aafont.c
    src/aalib/aafonts.c
    src/aalib/aahelp.c
    src/aalib/aaimage.c
    src/aalib/aaimgheight.c
    src/aalib/aaimgwidth.c
    src/aalib/aain.c
    src/aalib/aakbdreg.c
    src/aalib/aalib.c
    src/aalib/aalinux.c
    src/aalib/aalinuxkbd.c
    src/aalib/aamem.c
    src/aalib/aamktabl.c
    src/aalib/aammheight.c
    src/aalib/aammwidth.c
    src/aalib/aamoureg.c
    src/aalib/aaout.c
    src/aalib/aaparse.c
    src/aalib/aaprintf.c
    src/aalib/aaputpixel.c
    src/aalib/aarec.c
    src/aalib/aarecfunc.c
    src/aalib/aaregist.c
    src/aalib/aarender.c
    src/aalib/aasave.c
    src/aalib/aascrheight.c
    src/aalib/aascrwidth.c
    src/aalib/aastdin.c
    src/aalib/aastdout.c
    src/aalib/aatext.c
    src/aalib/font14.c
    src/aalib/font16.c
    src/aalib/font8.c
    src/aalib/font9.c
    src/aalib/fontcour.c
    src/aalib/fontgl.c
    src/aalib/fontline.c
    src/aalib/fontx13b.c
    src/aalib/fontx13.c
    src/aalib/fontx16.c
)

set(HASCIICAM_APP_SOURCES
    src/app/app_config.c
    src/app/app_session.c
    src/public/hasciicam_api.c
)

set(HASCIICAM_OUTPUT_SOURCES
    src/output/output.c
    src/output/output_file.c
    src/output/output_memory.c
)

set(HASCIICAM_RENDER_SOURCES
    src/render/render_session.c
)

set(HASCIICAM_CAPTURE_SOURCES
    src/capture/capture_backend.c
    src/capture/capture_external.c
    src/capture/capture_dshow.cpp
    src/capture/capture_mf.c
    src/capture/frame_convert.c
    src/capture/capture_v4l2.c
)

if(WIN32)
    list(APPEND HASCIICAM_AALIB_SOURCES src/compat/getopt.c)
endif()
