name: hasciicam
on:
  push:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
    branches:
      - master

jobs:
  linux-test:
    name: 🐧 Linux test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Cache APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: "gcc cmake ninja-build meson libsdl2-dev libx11-dev libncurses-dev"
      - name: Build
        run: |
          mkdir build && cd build && cmake .. -G Ninja && ninja

  win-test:
    name: 🪟 Windows native test
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v5
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          pkgs: sdl2
          triplet: x64-windows-release
          token: ${{ github.token }}
      - name: Build native windows exe for x86_64
        run: |
          mkdir build && cd build && cmake .. -G Ninja && ninja

  osx-test:
    name: 🍎 OSX native test
    runs-on: "macos-latest"
    steps:
      - uses: actions/checkout@v5
      - name: Build native Apple/OSX command executable
        run: |
          mkdir build && cd build && cmake .. -G Ninja && ninja
